import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { Header } from "../components/Header";
import AddTask from "../components/AddTask";
import TodoList from "../components/TodoList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TodoMaster</title>
        <meta name="description" content="Generated by create-t3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: todos } = api.todos.getAll.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  });

  return (
    <>
      {sessionData?.user ? (
        <main className="h-screen bg-primary-content">
          <Header />
          <div className="mx-auto mt-4 max-w-4xl px-4">
            <div className="my-5 flex flex-col gap-4 text-center">
              <AddTask />
            </div>
            <TodoList tasks={todos ? todos : []} />
          </div>
        </main>
      ) : (
        <main className="flex h-screen flex-col items-center justify-center bg-primary-content px-4 sm:px-6 lg:px-8">
          <h1 className="mb-4 text-center text-4xl font-bold text-primary sm:text-5xl">
            Welcome to TodoMaster
          </h1>
          <p className="mb-6 px-4 text-center text-base text-secondary sm:text-lg">
            Organize your tasks, manage your time, and increase productivity
            with TodoMaster.
          </p>
          <button
            onClick={() => void signIn()}
            className="btn btn-primary px-4 py-2 text-sm sm:px-6 sm:py-3 sm:text-base"
          >
            Sign In to Your Account
          </button>
        </main>
      )}
    </>
  );
};
